//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Address
    {
        public int AddressID { get; set; }
        public int UserID { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        //[Required(ErrorMessage = " 地址不能为空")]
        public string AddressDetail { get; set; }
        public int IsDefault { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
