//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.Adopt = new HashSet<Adopt>();
            this.AdoptResult = new HashSet<AdoptResult>();
            this.GoodsComments = new HashSet<GoodsComments>();
            this.OrderItems = new HashSet<OrderItems>();
            this.ShoppingCarts = new HashSet<ShoppingCarts>();
        }

        public int GoodsID { get; set; }
        public int ShopID { get; set; }
        [Required(ErrorMessage = "请输入商品名")]
        [RegularExpression(@"^[\\u4e00-\u9fa5_a-zA-Z0-9-\\w]{1,12}$", ErrorMessage = "限12个字符，支持中英文、数字、减号或下划线")]
        public string GoodsName { get; set; }
        [Required(ErrorMessage = "请输入价格")]
        [RegularExpression(@"\d+(\.){0,1}\d{0,2}", ErrorMessage = "请输入正确格式")]
        public decimal Price { get; set; }
        [Required]
        public string GoodsPhoto { get; set; }
        public string GoodsDescribe { get; set; }
        public Nullable<int> LikeIt { get; set; }
        [Required(ErrorMessage = "*")]
        public int Flag { get; set; }

        public Nullable<System.DateTime> Time { get; set; }
        [Required(ErrorMessage = "请输入库存")]
        [RegularExpression("^[0-9]*[1-9][0-9]*$", ErrorMessage = "只能输入正整数")]
        public int Stock { get; set; }
        public int Sales { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adopt> Adopt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdoptResult> AdoptResult { get; set; }
        public virtual Shops Shops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsComments> GoodsComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCarts> ShoppingCarts { get; set; }
    }
}
