//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PostComments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostComments()
        {
            this.ReplyPost = new HashSet<ReplyPost>();
        }
    
        public int PostCommentID { get; set; }
        public int UserID { get; set; }
        public int PostID { get; set; }
        [Required(ErrorMessage = "内容不能为空")]
        public string PostCommentContent { get; set; }
        public System.DateTime PostCommentTime { get; set; }
    
        public virtual Posts Posts { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplyPost> ReplyPost { get; set; }
    }
}
