//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pots
    {
        public int PotID { get; set; }
        public int UserID { get; set; }
        public int LevelID { get; set; }
        public int Experience { get; set; }
        public Nullable<System.DateTime> Sign { get; set; }
        public Nullable<int> SignDays { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Users Users { get; set; }
    }
}
