//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ReplyPost
    {
        public int ReplyPostID { get; set; }
        public int UserID { get; set; }
        public int PostCommentID { get; set; }
        [Required(ErrorMessage = "内容不能为空")]
        [StringLength(140, ErrorMessage = "最多输入140个字")]
        public string ReplyContent { get; set; }
        public System.DateTime ReplyPostTime { get; set; }
        public virtual PostComments PostComments { get; set; }
        public virtual Users Users { get; set; }
    }
}
