//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SucculentEntities : DbContext
    {
        public SucculentEntities()
            : base("name=SucculentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityCategory> ActivityCategory { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Adopt> Adopt { get; set; }
        public virtual DbSet<AdoptResult> AdoptResult { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<CharitableResult> CharitableResult { get; set; }
        public virtual DbSet<Collection> Collection { get; set; }
        public virtual DbSet<Donate> Donate { get; set; }
        public virtual DbSet<Entries> Entries { get; set; }
        public virtual DbSet<Farms> Farms { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<GoodsComments> GoodsComments { get; set; }
        public virtual DbSet<Level> Level { get; set; }
        public virtual DbSet<OrderItems> OrderItems { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PostComments> PostComments { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Pots> Pots { get; set; }
        public virtual DbSet<ReplyGoods> ReplyGoods { get; set; }
        public virtual DbSet<ReplyPost> ReplyPost { get; set; }
        public virtual DbSet<Sections> Sections { get; set; }
        public virtual DbSet<ShoppingCarts> ShoppingCarts { get; set; }
        public virtual DbSet<Shops> Shops { get; set; }
        public virtual DbSet<Succulent> Succulent { get; set; }
        public virtual DbSet<SucculentCategory> SucculentCategory { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
